#### Build and Push the image to ECR ###
version: 2.1
orbs:
  terraform: circleci/terraform@3.0.0
  aws-ecr: circleci/aws-ecr@7.2.0

workflows:
  # deploy_infrastructure:  #create an ECR Repository
  #   jobs:
  #     - terraform/validate:
  #         checkout: true
  #         context: terraform
  #         path: ./infra
  #     - terraform/plan:
  #         checkout: true
  #         context: terraform
  #         path: ./infra
  #         persist-workspace: true
  #         requires:
  #           - terraform/validate
  #     - review-terraform:
  #         type: approval
  #         requires:
  #           - terraform/plan
  #     - terraform/apply:
  #         attach-workspace: true
  #         context: terraform
  #         path: ./infra
  #         filters:
  #           branches:
  #             only: main
  #         requires:
  #           - review-terraform
  build_and_push_image:   #build and push image to ECR
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: .
          region: AWS_REGION
          tag: 'latest,1.0.0.${CIRCLE_BUILD_NUM}'